export default {
  SEARCH_HEROES_PENDING: 'SEARCH_HEROES_PENDING',
  SEARCH_HEROES_SUCCESS: 'SEARCH_HEROES_SUCCESS',
  SEARCH_HEROES_FAIL: 'SEARCH_HEROES_FAIL',
  GET_HERO_PENDING: 'GET_HERO_PENDING',
  GET_HERO_SUCCESS: 'GET_HERO_SUCCESS',
  GET_HERO_FAIL: 'GET_HERO_FAIL'
}
